import {test, expect} from '@playwright/test'

test("Decathlon ordering", async({page, context})=>{

    await page.goto("https://www.decathlon.in/")
    //console.log(await page.title())
    await page.locator("//span[@class='!mr-1']").first().click()
    await expect(page.getByPlaceholder("Search For 60+ Sports and 6000+ Products")).toBeEnabled()
    const search = await page.getByPlaceholder("Search For 60+ Sports and 6000+ Products")
    //await page.waitForTimeout(3000)
    search.fill("shoes")
    search.press("Enter")
    console.log(await page.title())
    await expect(page).toHaveTitle("Search | shoes")
    await page.locator("//span[@class='aisRefinementListLabelText']").first().click()
    await page.locator("//span[contains(text(),'Football boots')]").click()
    await page.locator("//span[contains(text(),'10.5')]").click()
    await page.locator("//span[text()='Most Relevant']").click()
    await page.locator("//a[text()='Price: High to Low']").click()
    await page.locator("//li[@class='ais-InfiniteHits-item']").first().click()
    await page.locator("//span[text()='BRAND SIZE']").click()
    await page.locator("//div[text()='UK 11 - EU 46']").click()
    //await page.waitForTimeout(3000)
    await page.getByLabel("addToCart").first().click()
    await page.waitForTimeout(3000)
    await page.locator("//p[text()='Cart']").click()
    await page.waitForTimeout(3000)
    const totalvalue= await page.locator("//div[@data-test-id='cart:cart-checkout-total-cart-value']").innerText()
    console.log(totalvalue)
    //await page.waitForTimeout(3000)
})